Update README.md
aiven/http-connector-for-apache-kafka pull request #169
Opened 2023-06-16 04:15 UTC by alberttwong

added clarification on the config file and how to submit it into kafka.

2023-06-20 06:34 UTC, jeqo requested changes
@alberttwong thanks! Just a couple of minor improvements.

2023-06-20 06:34 UTC, jeqo commented on README.md
> +An example of configuration (file connect-http-sink.json):
```suggestion
An example of configuration (file `connect-http-sink.json`):
```

2023-06-20 06:34 UTC, jeqo commented on README.md
> +Then execute the config json against the Apache Kafka REST API `curl -d @config/connect-http-sink.json -H "Content-Type: application/json" -X POST http://localhost:8083/connector`
```suggestion
Then deploy the connector configuration against the Kafka Connect REST API with the following command: 

```shell
curl -d @config/connect-http-sink.json -H "Content-Type: application/json" -X POST http://localhost:8083/connector
```

```

2023-06-20 19:43 UTC, alberttwong commented
done.

2023-06-21 07:32 UTC, jeqo requested changes
Thanks @alberttwong ! There's a last failing bit.

You can validate build process with `./gradlew :spotlessMiscCheck`

2023-06-21 07:32 UTC, jeqo commented on README.md
> +Then deploy the connector configuration against the Kafka Connect REST API with the following command:
```suggestion
Then deploy the connector configuration against the Kafka Connect REST API with the following command:
```

2023-06-21 22:27 UTC, jeqo approved these changes
Thanks @alberttwong !

2023-06-21 22:27 UTC, merged