Adding support for hashmap for the case of json value without a schema
aiven/http-connector-for-apache-kafka pull request #49
Opened 2021-12-20 10:09 UTC by Uriende

Relates to issue #48 
Added support for hashmap types.

Let me know if something else needs to be added or changed.

2022-01-03 09:31 UTC, jjaakola-aiven requested changes
@Uriende thank you for the contribution.

The change is good, if the `[key|value].converter.schemas.enable=false` and `org.apache.kafka.connect.json.JsonConverter` is used a HashMap is passed to record converter.

What I'd like to ask in addition is an integration test for reproduction and squashing to single commit.

2022-01-03 09:31 UTC, jjaakola-aiven commented on src/main/java/io/aiven/kafka/connect/http/converter/RecordValueConverter.java
> +                    "Record value must be String or Schema Struct or HashMap,"
```suggestion
                    "Record value must be String, Schema Struct or HashMap," 
```

2022-01-03 15:32 UTC, Uriende commented
@jjaakola-aiven Added a specific integration test for json and squashed. I've considered also testing json with a schema but the integration tests are using an older version of the confluent platform that doesn't yet support json with schema to my understanding.

2022-01-04 08:48 UTC, jjaakola-aiven requested changes
Thank you. There are two items to clean, wildcard imports and unnecessary schema container setup.

2022-01-04 08:48 UTC, jjaakola-aiven commented on src/integration-test/java/io/aiven/kafka/connect/http/JsonIntegrationTest.java
> +    private final SchemaRegistryContainer schemaRegistry = new SchemaRegistryContainer(kafka);
SchemaRegistryContainer is not used in this test and can be removed.

2022-01-04 08:48 UTC, jjaakola-aiven commented on src/integration-test/java/io/aiven/kafka/connect/http/JsonIntegrationTest.java
> +import org.junit.jupiter.api.*;
Expand wildcard imports.

2022-01-04 09:05 UTC, Uriende commented
Cleaned the imports and remvoed the unused container. Also added to copyright comment that I noticed was also missing from my file

2022-01-04 09:34 UTC, Uriende commented
Saw the issues. Sorry forgot to run the build locally. I'll fix everything now.

2022-01-04 12:35 UTC, jjaakola-aiven approved these changes

2022-01-04 12:36 UTC, merged